# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]
        architecture:
          - x64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Build Types
      run: yarn run build:types
    - name: Validate Formatting
      run: yarn run prettier:check
    - name: Validate Types
      run: NODE_OPTIONS=--max_old_space_size=9216 yarn run validate:types
    - name: Build Example
      run: yarn run build:example
    - name: Validate Example Typescript
      run: NODE_OPTIONS=--max_old_space_size=9216 yarn run validate:example
